local config = { 
	[1] = { 
		id = 1,
		firstlevel = 1,
		firstlevelname = "全部",
		stdmode = "5#6#10#11#15#16#19#20#21#22#23#24#26#64#54#62#52",
	},
	[2] = { 
		id = 2,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 1,
		secondlevelname = "全部",
		stdmode = "5#6#10#11#15#16#19#20#21#22#23#24#26#64#54#62#52",
	},
	[3] = { 
		id = 3,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 2,
		secondlevelname = "武器",
		stdmode = "5#6",
	},
	[4] = { 
		id = 4,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 3,
		secondlevelname = "衣服",
		stdmode = "10#11",
	},
	[5] = { 
		id = 5,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 4,
		secondlevelname = "头盔",
		stdmode = "15#16",
	},
	[6] = { 
		id = 6,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 5,
		secondlevelname = "项链",
		stdmode = "19#20#21",
	},
	[7] = { 
		id = 7,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 6,
		secondlevelname = "戒指",
		stdmode = "22#23",
	},
	[8] = { 
		id = 8,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 7,
		secondlevelname = "手镯",
		stdmode = "24#26",
	},
	[9] = { 
		id = 9,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 8,
		secondlevelname = "腰带",
		stdmode = "64#54",
	},
	[10] = { 
		id = 10,
		firstlevel = 2,
		firstlevelname = "装备",
		secondlevel = 9,
		secondlevelname = "鞋子",
		stdmode = "62#52",
	},
	[11] = { 
		id = 11,
		firstlevel = 3,
		firstlevelname = "特殊物品",
		secondlevel = 1,
		secondlevelname = "全部",
		stdmode = "31#42",
	},
	[12] = { 
		id = 12,
		firstlevel = 3,
		firstlevelname = "特殊物品",
		secondlevel = 3,
		secondlevelname = "特殊物品",
		stdmode = "31#42",
	},
}
return config
