local config = {
	[1] = {
		weight = 300,
		name = "暴击之爪",
		id = 1,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "获得相当于（10%+等级×0.5%）的暴击率.获得相当于（10%+等级×0.5%）的暴击伤害",
	},
	[2] = {
		weight = 500,
		name = "无敌斩",
		id = 2,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "获得技能 无敌斩，进入无敌状态，对周围敌人造成一次范围斩击，攻击力150%的物理伤害，持续2秒，冷却时间120秒",
	},
	[3] = {
		weight = 600,
		name = "单刀赴会",
		id = 3,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "单人未组队时.获得相当于（5%+等级×1%）的攻击.获得相当于（5%+等级×1%）的生命.获得相当于（5%+等级×1%）的防御",
	},
	[4] = {
		weight = 1000,
		name = "浴血奋战",
		id = 5,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "每损失10%的血量，自身提升10%的攻击力（在30%生命值时获得最大增益）",
	},
	[5] = {
		weight = 1000,
		name = "玻璃大炮",
		id = 6,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "减少30%最大生命值。造成15%对怪增伤，15%对人增伤",
	},
	[6] = {
		weight = 1000,
		name = "赏金猎人",
		id = 7,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "每击杀100只怪物，获得一个紫色品级以上的随机藏品",
	},
	[7] = {
		weight = 50,
		name = "王中王",
		id = 9,
		type = 1,
		colorName = "棱彩",
		color = "#bd4444",
		tips = "立即获得一套大于本身装备等阶的剑甲（最高给到6级星王套）",
	},
	[8] = {
		weight = 1000,
		name = "处刑官",
		id = 10,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "当目标当前生命值低于70%时，对其造成的伤害提升15%",
	},
	[9] = {
		weight = 1000,
		name = "致命节奏",
		id = 11,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "暴击率+10%，暴击时间/额外造成一次攻击等值伤害",
	},
	[10] = {
		weight = 1000,
		name = "连环斩",
		id = 13,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "连续命中同一目标5次后，第5次攻击额外造成一次等值伤害",
	},
	[11] = {
		weight = 100,
		name = "战意昂扬",
		id = 14,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "将最大生命值的3%转化为攻击力",
	},
	[12] = {
		weight = 2000,
		name = "弱化射线",
		id = 16,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "命中敌人时，使其造成的伤害降低15%，持续5秒，冷却时间60秒",
	},
	[13] = {
		weight = 2000,
		name = "破甲",
		id = 17,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "获得相当于角色等级×1%的攻击穿透",
	},
	[14] = {
		weight = 1000,
		name = "疾行战魂",
		id = 18,
		type = 1,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "移动速度+20%，但是攻击速度-15%",
	},
	[15] = {
		weight = 100,
		name = "作弊:紧急撤离",
		id = 19,
		type = 2,
		colorName = "黄金",
		color = "#e18a3b",
		tips = "使用后20秒立即安全撤离当前对局，无需前往撤离点",
	},
	[16] = {
		weight = 1000,
		name = "寒霜",
		id = 22,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击命中使目标移动速度降低20%，持续2秒，冷却时间10秒",
	},
	[17] = {
		weight = 300,
		name = "狂热者",
		id = 23,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "获得相当于（5%+角色等级×0.5%）的攻击速度",
	},
	[18] = {
		weight = 1000,
		name = "唯快不破",
		id = 24,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击速度加成的50%转化为额外伤害",
	},
	[19] = {
		weight = 2000,
		name = "铁骨",
		id = 25,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "受到暴击时，伤害降低20%",
	},
	[20] = {
		weight = 1000,
		name = "力王",
		id = 26,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "获得相当于（5% + 角色等级×0.5%）的攻击力",
	},
	[21] = {
		weight = 1000,
		name = "守护神盾",
		id = 31,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "获得相当于角色等级×1%最大生命值的护盾，冷却时间45秒",
	},
	[22] = {
		weight = 1000,
		name = "烈焰",
		id = 34,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，灼烧概率提升至100%",
		group = 1,
	},
	[23] = {
		weight = 1000,
		name = "火势蔓延",
		id = 35,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，攻击灼烧敌人时20%概率给全屏敌人施加灼烧效果",
		group = 1,
	},
	[24] = {
		weight = 1000,
		name = "持续升温",
		id = 36,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，对灼烧状态的敌人额外造成50%攻击增伤",
		group = 1,
	},
	[25] = {
		weight = 1000,
		name = "弱化火焰",
		id = 37,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，灼烧状态的敌人回血效率降低50%",
		group = 1,
	},
	[26] = {
		weight = 1000,
		name = "不灭焰",
		id = 38,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，灼烧时长翻倍，延长+3秒",
		group = 1,
	},
	[27] = {
		weight = 1000,
		name = "焚心爆",
		id = 39,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率灼烧敌人1%的最大对方生命值，每次灼烧有20%的概率触发双倍伤害",
		group = 1,
	},
	[28] = {
		weight = 100,
		name = "攻速进化",
		id = 40,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每击杀10只小怪，攻速增加1%（上限20层）",
		group = 2,
	},
	[29] = {
		weight = 500,
		name = "屠杀进化",
		id = 41,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每击杀1名玩家，攻击+15，生命+150（上限10层）",
		group = 2,
	},
	[30] = {
		weight = 300,
		name = "移速进化",
		id = 42,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每击杀10只小怪，增加1%的移速（上限20层）",
		group = 2,
	},
	[31] = {
		weight = 200,
		name = "噬魂进化",
		id = 43,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每击杀1只小怪，生命值+10，攻击+1（上限100层）",
		group = 2,
	},
	[32] = {
		weight = 200,
		name = "猎魔进化",
		id = 44,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每击杀1只精英怪，攻击+5，生命+50（上限20层）每击杀1只BOSS，攻击+10，生命+100（上限10层）",
		group = 2,
	},
	[33] = {
		weight = 2000,
		name = "散财童子",
		id = 45,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "击杀小怪概率掉落额外300金币",
		group = 3,
	},
	[34] = {
		weight = 500,
		name = "打了小的来大的",
		id = 46,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "击杀怪物概率召唤精英怪，概率刷新BOSS",
		group = 3,
	},
	[35] = {
		weight = 1000,
		name = "是藏品",
		id = 47,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "击杀小怪概率掉落随机藏品",
		group = 3,
	},
	[36] = {
		weight = 2000,
		name = "妙手空空",
		id = 48,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "开启宝箱速度提升100%（时间减半）",
		group = 3,
	},
	[37] = {
		weight = 500,
		name = "聚宝成锋",
		id = 49,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "当前总收益价值每满10000金币，+1攻击，+10生命",
		group = 3,
	},
	[38] = {
		weight = 100,
		name = "高频火符",
		id = 51,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率触发火符攻击，火符概率提升到50%",
		group = 4,
	},
	[39] = {
		weight = 300,
		name = "双生火符",
		id = 52,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率触发火符攻击，进化为双生火符",
		group = 4,
	},
	[40] = {
		weight = 500,
		name = "灼烧火符",
		id = 53,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率触发火符攻击，100%附带灼烧",
		group = 4,
	},
	[41] = {
		weight = 500,
		name = "爆裂火符",
		id = 54,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击15%概率触发火符攻击，伤害+50%",
		group = 4,
	},
	[42] = {
		weight = 500,
		name = "疾风锐眼",
		id = 55,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻速+10%，暴击率+10%",
		group = 5,
	},
	[43] = {
		weight = 300,
		name = "暴走齿轮",
		id = 56,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "暴击后攻击速度提升15%，持续3秒（可刷新，不叠加）",
		group = 5,
	},
	[44] = {
		weight = 300,
		name = "致命攻速",
		id = 57,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "获得（5%+等级×0.5）的攻速和暴击",
		group = 5,
	},
	[45] = {
		weight = 200,
		name = "狂飙",
		id = 58,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻速+10%，击杀角色后攻速翻倍持续5秒",
		group = 5,
	},
	[46] = {
		weight = 500,
		name = "花来",
		id = 59,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "学习隐身术，获得《花来》技能，主动释放后10秒内 角色移速增加50%，120秒CD",
		group = 6,
	},
	[47] = {
		weight = 1000,
		name = "影遁",
		id = 60,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "学习隐身术，隐身时间+3秒",
		group = 6,
	},
	[48] = {
		weight = 1000,
		name = "轻身如燕",
		id = 61,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "学习隐身术，移速+20%",
		group = 6,
	},
	[49] = {
		weight = 1000,
		name = "绝境逢生",
		id = 62,
		type = 1,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "学习隐身术，生命值低于35%时，获得20%最大生命值护盾（持续3秒）和30%移动速度加成（持续3秒），冷却时间75秒",
		group = 6,
	},
	[50] = {
		weight = 1000,
		name = "调息",
		id = 63,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "学习隐身术，脱战状态下每秒回复自身1%生命值",
		group = 6,
	},
	[51] = {
		weight = 2000,
		name = "变羊术",
		id = 64,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "你的攻击20%概率将对手变成羊，对手无法释放任何技能，持续2秒",
		group = 7,
	},
	[52] = {
		weight = 2000,
		name = "寒冰锁",
		id = 65,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "你的攻击20%概率冰冻对手一秒，持续2秒",
		group = 7,
	},
	[53] = {
		weight = 2000,
		name = "烈焰震退",
		id = 66,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "生命值低于35%时，击退周围敌人并使其减速40%，持续2秒，冷却时间75秒",
		group = 7,
	},
	[54] = {
		weight = 500,
		name = "重锤定身",
		id = 67,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每5次攻击，概率对敌人造成一次重击伤害，并眩晕1秒",
		group = 7,
	},
	[55] = {
		weight = 2000,
		name = "控制欲极强",
		id = 68,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每对角色触发一次控制，攻击增加+5，生命+50 上限10层（变羊、冰冻、眩晕、击退）",
		group = 7,
	},
	[56] = {
		weight = 1000,
		name = "甘霖",
		id = 70,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "同时习得治愈术和神圣战甲术，范围内友军生命值低于30%时，立即为其回复15%最大生命值（每目标CD 60秒）",
		group = 8,
	},
	[57] = {
		weight = 1000,
		name = "铁壁光环",
		id = 71,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "同时习得治愈术和神圣战甲术，释放神圣战甲术时，自己周围3格内友军双防增加5%，持续30秒",
		group = 8,
	},
	[58] = {
		weight = 1000,
		name = "灵盾",
		id = 72,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "同时习得治愈术和神圣战甲术，每30秒为周围友军施加护盾，护盾值为自身最大生命值5%，持续5秒",
		group = 8,
	},
	[59] = {
		weight = 1000,
		name = "开箱赐福",
		id = 73,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "同时习得治愈术和神圣战甲术，每一次开启宝箱，都可为周围20码内友军回复5%最大生命值",
		group = 8,
	},
	[60] = {
		weight = 1000,
		name = "泰坦之躯",
		id = 74,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "体型增大30%，最大生命值+30%，防御力+15%",
		group = 9,
	},
	[61] = {
		weight = 1000,
		name = "星界屏障",
		id = 75,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "最大生命值+30%，造成的伤害降低15%",
		group = 9,
	},
	[62] = {
		weight = 1000,
		name = "坦克引擎",
		id = 76,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "击杀敌人时，体型增大3%并提升3%最大生命值，层数可无限叠加",
		group = 9,
	},
	[63] = {
		weight = 1000,
		name = "铁甲觉醒",
		id = 77,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "每受到1000点伤害，本局防御力永久+1，生命永久+10（上限50层）",
		group = 9,
	},
	[64] = {
		weight = 200,
		name = "肉装重击",
		id = 78,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击时附加自身最大生命值2%的额外物理伤害",
		group = 9,
	},
	[65] = {
		weight = 1000,
		name = "金钟罩",
		id = 79,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "受击时20%概率触发短暂“金钟罩”，无敌两秒（CD 45秒）",
		group = 9,
	},
	[66] = {
		weight = 800,
		name = "我小我牛B",
		id = 80,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "体型缩小30%，对比自己体型大的对手每大10%增加5%对人增伤",
		group = 10,
	},
	[67] = {
		weight = 1000,
		name = "专揍大高个",
		id = 81,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "当敌人体型大于自己时，攻击无视对手100%防御",
		group = 10,
	},
	[68] = {
		weight = 1000,
		name = "以小搏大",
		id = 82,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "对生命值高于50%的敌人造成的伤害提升30%",
		group = 10,
	},
	[69] = {
		weight = 1000,
		name = "蚁噬",
		id = 83,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "攻击附带目标最大生命值1%的真实伤害（无视无敌状态）",
		group = 10,
	},
	[70] = {
		weight = 1000,
		name = "巨人收割机",
		id = 84,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "击杀体型大于自己的敌人时，永久获得50攻击力（上限50层）",
		group = 10,
	},
	[71] = {
		weight = 500,
		name = "二次召唤",
		id = 86,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "习得神兽召唤技能，神兽召唤数量+1",
		group = 11,
	},
	[72] = {
		weight = 100,
		name = "神兽狂化",
		id = 87,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "习得神兽召唤技能，神兽攻击+20%，生命值+20%，攻速+20%",
		group = 11,
	},
	[73] = {
		weight = 600,
		name = "亡灵军团",
		id = 88,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "习得神兽召唤技能，攻击时有5%概率召唤一只骷髅战士协助战斗（最多同时存在5只）",
		group = 11,
	},
	[74] = {
		weight = 300,
		name = "万兽共鸣",
		id = 89,
		type = 2,
		colorName = "白银",
		color = "#f2f2f2",
		tips = "习得神兽召唤技能，每拥有一只召唤物，所有召唤物攻击+1%，生命值+1%",
		group = 11,
	},
	basic = {
		need = {
			[1] = {
				[1] = "元宝",
				[2] = 10,
			},
			[2] = {
				[1] = "元宝",
				[2] = 50,
			},
			[3] = {
				[1] = "元宝",
				[2] = 100,
			},
			[4] = {
				[1] = "元宝",
				[2] = 100,
			},
			[5] = {
				[1] = "元宝",
				[2] = 100,
			},
			[6] = {
				[1] = "元宝",
				[2] = 100,
			},
		},
	},
	["1"] = {
		group = 1,
	},
	["2"] = {
		group = 2,
	},
	["3"] = {
		group = 3,
	},
	["5"] = {
		group = 4,
	},
	["6"] = {
		group = 5,
	},
	["7"] = {
		group = 6,
	},
	["9"] = {
		group = 7,
	},
	["10"] = {
		group = 8,
	},
	["11"] = {
		group = 9,
	},
	["13"] = {
		group = 10,
	},
	["14"] = {
		group = 11,
	},
	["16"] = {
		group = 12,
	},
	["17"] = {
		group = 13,
	},
	["18"] = {
		group = 14,
	},
	["19"] = {
		group = 15,
	},
	["22"] = {
		group = 16,
	},
	["23"] = {
		group = 17,
	},
	["24"] = {
		group = 18,
	},
	["25"] = {
		group = 19,
	},
	["26"] = {
		group = 20,
	},
	["31"] = {
		group = 21,
	},
	["34"] = {
		group = 22,
	},
	["35"] = {
		group = 23,
	},
	["36"] = {
		group = 24,
	},
	["37"] = {
		group = 25,
	},
	["38"] = {
		group = 26,
	},
	["39"] = {
		group = 27,
	},
	["40"] = {
		group = 28,
	},
	["41"] = {
		group = 29,
	},
	["42"] = {
		group = 30,
	},
	["43"] = {
		group = 31,
	},
	["44"] = {
		group = 32,
	},
	["45"] = {
		group = 33,
	},
	["46"] = {
		group = 34,
	},
	["47"] = {
		group = 35,
	},
	["48"] = {
		group = 36,
	},
	["49"] = {
		group = 37,
	},
	["51"] = {
		group = 38,
	},
	["52"] = {
		group = 39,
	},
	["53"] = {
		group = 40,
	},
	["54"] = {
		group = 41,
	},
	["55"] = {
		group = 42,
	},
	["56"] = {
		group = 43,
	},
	["57"] = {
		group = 44,
	},
	["58"] = {
		group = 45,
	},
	["59"] = {
		group = 46,
	},
	["60"] = {
		group = 47,
	},
	["61"] = {
		group = 48,
	},
	["62"] = {
		group = 49,
	},
	["63"] = {
		group = 50,
	},
	["64"] = {
		group = 51,
	},
	["65"] = {
		group = 52,
	},
	["66"] = {
		group = 53,
	},
	["67"] = {
		group = 54,
	},
	["68"] = {
		group = 55,
	},
	["70"] = {
		group = 56,
	},
	["71"] = {
		group = 57,
	},
	["72"] = {
		group = 58,
	},
	["73"] = {
		group = 59,
	},
	["74"] = {
		group = 60,
	},
	["75"] = {
		group = 61,
	},
	["76"] = {
		group = 62,
	},
	["77"] = {
		group = 63,
	},
	["78"] = {
		group = 64,
	},
	["79"] = {
		group = 65,
	},
	["80"] = {
		group = 66,
	},
	["81"] = {
		group = 67,
	},
	["82"] = {
		group = 68,
	},
	["83"] = {
		group = 69,
	},
	["84"] = {
		group = 70,
	},
	["86"] = {
		group = 71,
	},
	["87"] = {
		group = 72,
	},
	["88"] = {
		group = 73,
	},
	["89"] = {
		group = 74,
	},
}
return config