EventCfg = {}

--引擎事件
EventCfg.onNewHuman                 = "onNewHuman"                    --新角色第一次登录    (参数：actor)
EventCfg.onLogin                    = "onLogin"                       --登录    (参数：actor)
EventCfg.onLoginAttr                = "onLoginAttr"                   --登录附加属性    (参数：actor, 登录属性数据)
EventCfg.onLoginEnd                 = "onLoginEnd"                    --登录完成    (参数：actor, 登录同步数据)
EventCfg.onKillMon                  = "onKillMon"                     --任意地图杀怪    (参数：actor, 死亡怪物对象, 死亡怪物idx)
EventCfg.onKillPlay                 = "onKillPlay"                    --任意地图杀人
EventCfg.onPlayLevelUp              = "onPlayLevelUp"                 --玩家升级    (参数：actor, 当前等级, 之前等级)
EventCfg.onAddBag                   = "onAddBag"                      --物品进背包
EventCfg.onExitGame                 = "onExitGame"                    --小退或大退游戏
EventCfg.onTriggerChat              = "onTriggerChat"                 --聊天栏输入信息
EventCfg.onClickNpc                 = "onClickNpc"                    --点击某NPC
EventCfg.onRecharge                 = "onRecharge"                    --充值     (参数：actor, 充值rmb金额, 产品ID（保留）, 货币ID)
EventCfg.onEnterMap                 = "onEnterMap"                    --进入地图
EventCfg.noSwitchMap                = "noSwitchMap"                   --切换地图
EventCfg.onLoadAttr                 = "onLoadAttr"                    --加载属性
EventCfg.onTitleShow                = "onTitleShow"                   --加载顶戴
EventCfg.onTimeGift                 = "onTimeGift"                    --加载右上图标
EventCfg.onRedPoint                 = "onRedPoint"                    --加载红点
EventCfg.onBtnShow                  = "onBtnShow"                     --加载气泡
EventCfg.onRecycle                  = "onRecycle"                     --回收
EventCfg.onHeiShi                   = "onHeiShi"                      --黑市初始化
EventCfg.onLevelName                = "onLevelName"                   --加载称谓
EventCfg.onUp                       = "onUp"                          --加载称谓
EventCfg.onAttrBuff                 = "onAttrBuff"                    --总属性buff
EventCfg.onTitleChange              = "onTitleChange"                 --称号更换
EventCfg.onTakeChange               = "onTakeChange"                  --穿脱装备
EventCfg.onLeaveMap                 = "onLeaveMap"                    --离开地图触发
EventCfg.onTaskChange               = "onTaskChange"                  --任务变化
EventCfg.onAttackMon                = "onAttackMon"                   --攻击怪物
EventCfg.onLoadQF                   = "onLoadQF"                      --重载QF
EventCfg.onTaskFinish               = "onTaskFinish"                  --任务完成
EventCfg.onAttackDamage             = "onAttackDamage"                --攻击前触发
EventCfg.onStruckDamage             = "onStruckDamage"                --受攻击前触发
EventCfg.onRun                      = "onRun"                         --跑步触发
EventCfg.onXiuXian                  = "onXiuXian"                     --修仙模拟器插入数据
EventCfg.onDelBuff                  = "onDelBuff"                     --删除buff
EventCfg.onAddBuff                  = "onAddBuff"                     --添加buff
EventCfg.onSystemCache              = "onSystemCache"                 --系统缓存
EventCfg.onCollectMonEx             = "onCollectMonEx"                --收集怪物
EventCfg.onAddCards                 = "onAddCards"                    --增加一次卡牌
EventCfg.onAddBagArtifact           = "onAddBagArtifact"              --添加背包神器
EventCfg.onMonDropItemEx            = "onMonDropItemEx"               --怪物掉落物品触发
EventCfg.onChangeJinBi              = "onChangeJinBi"                 --金币改变
EventCfg.onChangeYuanBao            = "onChangeYuanBao"               --金币改变
EventCfg.onAutoPlayGame             = "onAutoPlayGame"                --自动挂机
EventCfg.onRage                     = "onRage"                        --开启狂暴之力
EventCfg.onKillRage                 = "onKillRage"                    --击杀狂暴
EventCfg.onGroupChange              = "onGroupChange"                 --组队变化
EventCfg.onGuildChange              = "onGuildChange"                 --行会变化
EventCfg.onPKChange                 = "onPKChange"                    --PK值变化
EventCfg.onRealive                  = "onRealive"                     --复活触发
EventCfg.onPlayDie                  = "onPlayDie"                     --被杀触发
EventCfg.onNextDie                  = "onNextDie"                     --死亡前触发
EventCfg.onBeginMagic               = "onBeginMagic"                  --释放技能前触发
EventCfg.onRein                     = "onRein"                        --转生触发
EventCfg.onDuJie                    = "onDuJie"                       --渡劫
EventCfg.onAllAttrChange            = "onAllAttrChange"               --所有属性变化
EventCfg.onCrit                     = "onCrit"                        --暴击触发
EventCfg.onSuitChange               = "onSuitChange"                  --套装变化
EventCfg.onTimer1                   = "onTimer1"                      --1分钟定时器
EventCfg.onControl                  = "onControl"                     --控制触发
EventCfg.onTaskCompleted            = "onTaskCompleted"               --任务完成
EventCfg.onPushRedPoint             = "onPushRedPoint"                --推送红点变强
EventCfg.onCheckAttr                = "onCheckAttr"                   --检测自定义属性重新加载
EventCfg.onBuffHpChange             = "onBuffHpChange"                --buff触发血量改变时
EventCfg.onGuildDelMember           = "onGuildDelMember"              --离开行会
EventCfg.onGuildClose               = "onGuildClose"                  --行会解散
--游戏事件
EventCfg.goDeclareVar               = "goDeclareVar"                  --声明全局变量
EventCfg.goPlayerVar                = "goPlayerVar"                   --声明个人变量    (参数：actor)
EventCfg.goZSLevelChange            = "goZSLevelChange"               --转生等级发生变化 (参数：actor, 当前转生等级， 之前的转生等级)
EventCfg.goBeforedawn               = "goBeforedawn"                  --机器人脚本每日凌晨触发  (参数：actor, 凌晨同步数据)
EventCfg.roBeforedawn               = "roBeforedawn"                  --机器人脚本每日凌晨触发 (已开服天数)
EventCfg.goDailyUpdate              = "goDailyUpdate"                 --每日更新(凌晨或每日第一次登录)(参数：actor, 是否每日第一次登录, 同步数据)
EventCfg.goCheckModule              = "goCheckModule"                 --检查是否有模块达到开启要求
EventCfg.goOpenModule               = "goOpenModule"                  --某模块达到开启要求(参数：actor, 模块ID)
EventCfg.onPickUpItemEx             = "onPickUpItemEx"                --拾取物品后触发(参数：actor, item，--等待支持num)
EventCfg.goCastlewarend             = "goCastlewarend"                --攻城结束时触发
EventCfg.gocastlewarstart           = "gocastlewarstart"              --攻城开始时触发
EventCfg.gomapeventwalk             = "gomapeventwalk"                --沙巴克进皇宫走步触发
EventCfg.goActivityState            = "goActivityState"               --活动开启或关闭展示红点(参数 活动idx,活动state)
EventCfg.onClickIcon                = "onClickIcon"                   --点击图标
EventCfg.onOutputRecord             = "onOutputRecord"                --产出记录 (参数：actor, data)
EventCfg.onConsumeRecord            = "onConsumeRecord"               --消耗记录 (参数：actor, data)

return EventCfg