-- 不要在其他脚本对该表进行操作,个人常量表
Constant = {
    --- @field [parent=#Constant] #table CHINA_NUM 中文数字
    CHINA_NUM = {
        [0] = "零",
        "一", "二", "三", "四", "五", "六", "七", "八", "九", "十",
        --"十一", "十二", "十三", "十四", "十五", "十六", "十七", "十八", "十九", "二十",
        --"二十一", "二十二", "二十三", "二十四", "二十五", "二十六", "二十七", "二十八", "二十九", "三十",
        --"三十一", "三十二", "三十三", "三十四", "三十五", "三十六", "三十七", "三十八", "三十九", "四十",
        --"四十一", "四十二", "四十三", "四十四", "四十五", "四十六", "四十七", "四十八", "四十九", "五十",
        --"五十一", "五十二", "五十三", "五十四", "五十五", "五十六", "五十七", "五十八", "五十九", "六十",
        --"六十一", "六十二", "六十三", "六十四", "六十五", "六十六", "六十七", "六十八", "六十九", "七十",
    },

    --- @field [parent=#Constant] #table WARN_MSG_TB 警告信息表
    WARN_MSG_TB={
        Msg="",
        FColor=nil,
        BColor=nil,
        Type=1,
        Time=nil,
        SendName=nil,
        SendId=nil
    },
    --- @field [parent=#Constant] #table PROGRESS_TB 警告信息表
    PROGRESS_TB = {
        open=1,
        show=1,
        name="",
        color=3,
        imgcolor=0,
        cur=0,
        max=100,
        level=0,
    },
    --- @field [parent=#Constant] #table EQUIP_POS_DIC  装备位置字典 1-道具类型	2-数据库stdmode 3-穿戴位置 4-位置常量 5-位置唯一ID常量(取下保留对应唯一ID)
    EQUIP_POS_DIC = {
        -- 道具类型	数据库stdmode	穿戴位置	位置常量	位置唯一ID常量(取下保留对应唯一ID)
        {"衣服(男)",{10},0,"<$DRESS>","<$DRESSID>"},
        {"衣服(女)",{11},0,"<$DRESS>","<$DRESSID>"},
        {"武器(男)",{5,6},1,"<$WEAPON>","<$WEAPONID>"},
        {"武器(女)",{5,6},1,"<$WEAPON>","<$WEAPONID>"},
        {"勋章",{30},2,"<$RIGHTHAND>","<$RIGHTHANDID>"},
        {"项链",{19,20,21},3,"<$NECKLACE>","<$NECKLACEID>"},
        {"头盔",{15},4,"<$HELMET>","<$HELMETID>"},
        {"右手镯",{24,26},5,"<$ARMRING_R>","<$ARMRING_RID>"},
        {"左手镯",{24,26},6,"<$ARMRING_L>","<$ARMRING_LID>"},
        {"右戒指",{22,23},7,"<$RING_R>","<$RING_RID>"},
        {"左戒指",{22,23},8,"<$RING_L>","<$RING_LID>"},
        {"符、毒药",{25},9,"<$BUJUK>","<$BUJUKID>"},
        {"腰带",{54,64},10,"<$BELT>","<$BELTID>"},
        {"靴子",{52,62},11,"<$BOOTS>","<$BOOTSID>"},
        {"宝石、血石",{53,63,7},12,"<$CHARM>","<$CHARMID>"},
        {"斗笠",{16},13,"<$HAT>","<$HATID>"},
        {"军鼓",{65},14,"<$DRUM>","<$DRUMID>"},
        {"马牌",{28},15,"<$HORSE>","<$HORSEID>"},
        {"盾牌",{48},16,"<$SHIELD>","<$SHIELDID>"},
        {"面巾",{50},55,"<$FTOWEL>","<$FTOWELID>"},
        {"时装衣服(男)",{66},17,"<$SDRESS>","<$SDRESSID>"},
        {"时装衣服(女)",{67},17,"<$SDRESS>","<$SDRESSID>"},
        {"时装武器(男)",{68},18,"<$SWEAPON>","<$SWEAPONID>"},
        {"时装武器(女)",{69},18,"<$SWEAPON>","<$SWEAPONID>"},
        {"时装斗笠",{71},19,"<$SHAT>","<$SHATID>"},
        {"时装项链",{75,76,77},20,"<$SNECKLACE>","<$SNECKLACEID>"},
        {"时装头盔",{78},21,"<$SHELMET>","<$SHELMETID>"},
        {"时装左手镯",{79,80},22,"<$SARMRING_L>","<$SARMRING_LID>"},
        {"时装右手镯",{79,80},23,"<$SARMRING_R>","<$SARMRING_RID>"},
        {"时装左戒指",{81,82},24,"<$SRING_L>","<$SRING_LID>"},
        {"时装右戒指",{81,82},25,"<$SRING_R>","<$SRING_RID>"},
        {"时装勋章",{83},26,"<$SRIGHTHAND>","<$SRIGHTHANDID>"},
        {"时装腰带",{84,85},27,"<$SBELT>","<$SBELTID>"},
        {"时装靴子",{86,87},28,"<$SBOOTS>","<$SBOOTSID>"},
        {"时装宝石",{88,89},29,"<$SCHARM>","<$SCHARMID>"},
        {"时装马牌",{90},42,"<$SHORSE>","<$SHORSEID>"},
        {"时装符印",{91},43,"<$SBUJUK>","<$SBUJUKID>"},
        {"时装军鼓",{92},44,"<$SDRUM>","<$SDRUMID>"},
        {"时装盾牌",{93},45,"<$SSHIELD>","<$SSHIELDID>"},
        {"时装面巾",{94},46,"<$SFTOWEL>","<$SFTOWELID>"},
        {"首饰盒位置1",{100},30,"<$GODBLESSITEM1>","<$GODBLESSITEM1ID>"},
        {"首饰盒位置2",{101},31,"<$GODBLESSITEM2>","<$GODBLESSITEM2ID>"},
        {"首饰盒位置3",{102},32,"<$GODBLESSITEM3>","<$GODBLESSITEM3ID>"},
        {"首饰盒位置4",{103},33,"<$GODBLESSITEM4>","<$GODBLESSITEM4ID>"},
        {"首饰盒位置5",{104},34,"<$GODBLESSITEM5>","<$GODBLESSITEM5ID>"},
        {"首饰盒位置6",{105},35,"<$GODBLESSITEM6>","<$GODBLESSITEM6ID>"},
        {"首饰盒位置7",{106},36,"<$GODBLESSITEM7>","<$GODBLESSITEM7ID>"},
        {"首饰盒位置8",{107},37,"<$GODBLESSITEM8>","<$GODBLESSITEM8ID>"},
        {"首饰盒位置9",{108},38,"<$GODBLESSITEM9>","<$GODBLESSITEM9ID>"},
        {"首饰盒位置10",{109},39,"<$GODBLESSITEM10>","<$GODBLESSITEM10ID>"},
        {"首饰盒位置11",{110},40,"<$GODBLESSITEM11>","<$GODBLESSITEM11ID>"},
        {"首饰盒位置12",{111},41,"<$GODBLESSITEM12>","<$GODBLESSITEM12ID>"},
    },
}

return Constant